'use client';
import { SessionProvider } from 'next-auth/react';
import { Arimo, Josefin_Sans } from 'next/font/google';
import React, { useEffect } from 'react';
import { Toaster } from 'react-hot-toast';
import socketIO from 'socket.io-client';
import { ThemeProvider } from '../components/theme/ThemeProvider';
import './globals.css';
import { Providers } from './Provider';
import { useLoadUserQuery } from '../redux/features/api/apiSlice';
import Loading from '../components/common/Loading';
const ENPOINT = process.env.NEXT_PUBLIC_SOCKET_API_SERVER_URL || '';
const socketId = socketIO(ENPOINT, {
  transports: ['websocket']
});

const josefin = Josefin_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-Josefin'
});
const arimo = Arimo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-Arimo'
});

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app'
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    socketId.on('connection', () => {});
  }, []);
  return (
    <html lang="en">
      <body
        className={`${arimo.variable} ${josefin.variable} !bg-white bg-no-repeat dark:bg-gradient-to-b dark:from-gray-900 dark:to-black`}
        //  duration-300
      >
        <Providers>
          <SessionProvider>
            <ThemeProvider attribute="class" enableSystem={false}>
              {/* <Custom>{children}</Custom> */}
              {children}
              <Toaster position="top-center" reverseOrder={false} />
            </ThemeProvider>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}

// const Custom: React.FC<{ children: React.ReactNode }> = ({ children }) => {
//   const { isLoading } = useLoadUserQuery({});
//   useEffect(() => {
//     socketId.on('connection', () => {});
//   }, []);
//   return <>{isLoading ? <Loading /> : children}</>;
// };
