'use client';
import { SessionProvider } from 'next-auth/react';
import { Josefin_Sans, Poppins } from 'next/font/google';
import React, { useCallback } from 'react';
import { Toaster } from 'react-hot-toast';
import Loading from '../components/common/Loading';
import { ThemeProvider } from '../components/theme/ThemeProvider';
import { useLoadUserQuery } from '../redux/features/api/apiSlice';
import './globals.css';
import { Providers } from './Provider';

const poppins = Poppins({
   subsets: ['latin'],
   weight: ['400', '500', '600', '700'],
   variable: '--font-Poppins'
});

const josefin = Josefin_Sans({
   subsets: ['latin'],
   weight: ['400', '500', '600', '700'],
   variable: '--font-Josefin'
});

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app'
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body
            className={`${poppins.variable} ${josefin.variable} !bg-white bg-no-repeat dark:bg-gradient-to-b dark:from-gray-900 dark:to-black`}
            //  duration-300
         >
            <Providers>
               <SessionProvider>
                  <ThemeProvider attribute="class" defaultTheme={'system'} enableSystem>
                     <Custom>{children}</Custom>
                     <Toaster position="top-center" reverseOrder={false} />
                  </ThemeProvider>
               </SessionProvider>
            </Providers>
         </body>
      </html>
   );
}

const Custom: React.FC<{ children: React.ReactNode }> = ({ children }) => {
   const { isLoading, isFetching, refetch, isUninitialized } = useLoadUserQuery({});
   //    const refetchTeam = useCallback(() => {
   //       if (!isUninitialized) {
   //          refetch();
   //       }
   //    }, [isUninitialized, refetch]);
   return <>{isLoading || isFetching ? <Loading /> : children}</>;
};
